vich_uploader:
    db_driver: orm

    mappings:
        standard_images: # this is a type of image it would be many types in a project such as profile_pictures , image , inspection_image
            uri_prefix: /images
            upload_destination: '%kernel.project_dir%/public/images'
            # Decide how uploaded files would be renamed
            namer: Vich\UploaderBundle\Naming\UniqidNamer
